version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080" # Spark Master Web UI
      - "7077:7077" # Spark Master Port
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    networks:
      spark-net:
        ipv4_address: 168.16.0.2
    deploy:
      resources:
        limits:
          cpus: "1" # Adjust CPU limit as needed
          memory: 2g # Adjust memory limit as needed

  spark-worker-1:
    image: bitnami/spark:latest
    container_name: spark-worker-1
    hostname: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_PORT=8881
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    ports:
      - "8081:8881"
    networks:
      spark-net:
        ipv4_address: 168.16.0.3
    deploy:
      resources:
        limits:
          cpus: "3" # Adjust CPU limit as needed
          memory: 10g # Adjust memory limit as needed
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:latest
    container_name: spark-worker-2
    hostname: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8G
      - SPARK_WORKER_PORT=8881
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    ports:
      - "8082:8881"
    networks:
      spark-net:
        ipv4_address: 168.16.0.4
    deploy:
      resources:
        limits:
          cpus: "3" # Adjust CPU limit as needed
          memory: 10g # Adjust memory limit as needed
    depends_on:
      - spark-master

networks:
  spark-net:
    driver: bridge
    ipam:
      config:
        - subnet: 168.16.0.0/24

